language: node_js
node_js:
  - "8" # stable
  - "6" # LTS
  - "4" # maintenance
sudo: false
cache:
  directories:
    - node_modules
after_script: ./node_modules/.bin/coveralls < coverage/lcov.info
notifications:
  email: false
